services:

  db:
    ports:
      - 3306:3306

  app:
    init: true
    ports:
      - 3000:3000
      - 24678:24678
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEV_ENV=true

  php:
    environment:
      - DEV_ENV=true
