services:

  nginx:
    build: ./nginx
    env_file: .env
    networks:
      internal:
        ipv4_address: 10.5.0.10
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./api/:/var/www/html/api:ro
      - ./app/dist:/var/www/html/app:ro
      - ./storage/graphics:/var/www/html/storage/graphics:ro
      - ./storage/music:/var/www/html/storage/music:ro
      - ./storage/map_previews:/var/www/html/storage/map_previews:ro
    depends_on:
      - php
      - app
    extra_hosts:
      api.idgames.local: 10.5.0.10
      app.idgames.local: 10.5.0.10
      storage.idgames.local: 10.5.0.10

  php:
    build: ./php
    env_file: .env
    networks:
      internal:
        ipv4_address: 10.5.0.20
    expose:
      - 9000
    volumes:
      - ./api/:/var/www/html/api
      - ./php/php-extra.ini:/usr/local/etc/php/conf.d/php-extra.ini
    depends_on:
      - db

  db:
    build: ./db
    env_file: .env
    networks:
      internal:
        ipv4_address: 10.5.0.30
    expose:
      - 3306
    volumes:
      - ./storage/db:/var/lib/mysql/

  app:
    build: ./app
    env_file: .env
    networks:
      internal:
        ipv4_address: 10.5.0.40
    volumes:
      - ./app/:/var/app
    extra_hosts:
      api.idgames.local: 10.5.0.10
      storage.idgames.local: 10.5.0.10

  indexer:
    build: ./indexer
    env_file: .env
    init: true
    networks:
      internal:
        ipv4_address: 10.5.0.50
    volumes:
      - ./indexer:/usr/src/app
      - "$INDEXER_PATH_COLLECTIONS:/var/collections"
      - "$INDEXER_PATH_IWADS:/var/iwads:ro"
      - ./storage/logs:/var/log/indexer
      - ./storage/graphics:/var/indexer/storage/graphics
      - ./storage/music:/var/indexer/storage/music
      - ./storage/map_previews:/var/indexer/storage/map_previews
    depends_on:
      - db


networks:

  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
