from indexer.game import Game

MUSIC_STRINGS = {
    Game.DOOM: {
        'maps': {
            'E1M1': 'd_e1m1',
            'E1M2': 'd_e1m2',
            'E1M3': 'd_e1m3',
            'E1M4': 'd_e1m4',
            'E1M5': 'd_e1m5',
            'E1M6': 'd_e1m6',
            'E1M7': 'd_e1m7',
            'E1M8': 'd_e1m8',
            'E1M9': 'd_e1m9',
            'E2M1': 'd_e2m1',
            'E2M2': 'd_e2m2',
            'E2M3': 'd_e2m3',
            'E2M4': 'd_e2m4',
            'E2M5': 'd_e2m5',
            'E2M6': 'd_e2m6',
            'E2M7': 'd_e2m7',
            'E2M8': 'd_e2m8',
            'E2M9': 'd_e2m9',
            'E3M1': 'd_e3m1',
            'E3M2': 'd_e3m2',
            'E3M3': 'd_e3m3',
            'E3M4': 'd_e3m4',
            'E3M5': 'd_e3m5',
            'E3M6': 'd_e3m6',
            'E3M7': 'd_e3m7',
            'E3M8': 'd_e3m8',
            'E3M9': 'd_e3m9',
            'E4M1': 'D_E3M4',
            'E4M2': 'D_E3M2',
            'E4M3': 'D_E3M3',
            'E4M4': 'D_E1M5',
            'E4M5': 'D_E2M7',
            'E4M6': 'D_E2M4',
            'E4M7': 'D_E2M6',
            'E4M8': 'D_E2M5',
            'E4M9': 'D_E1M9',
        },
        'extra': {
            'D_INTER',
            'D_INTRO',
            'D_INTROA',
            'D_VICTOR',
            'D_BUNNY',
        }
    },

    Game.DOOM2: {
        'maps': {
            'MAP01': 'D_RUNNIN',
            'MAP02': 'D_STALKS',
            'MAP03': 'D_COUNTD',
            'MAP04': 'D_BETWEE',
            'MAP05': 'D_DOOM',
            'MAP06': 'D_THE_DA',
            'MAP07': 'D_SHAWN',
            'MAP08': 'D_DDTBLU',
            'MAP09': 'D_IN_CIT',
            'MAP10': 'D_DEAD',
            'MAP11': 'D_STLKS2',
            'MAP12': 'D_THEDA2',
            'MAP13': 'D_DOOM2',
            'MAP14': 'D_DDTBL2',
            'MAP15': 'D_RUNNI2',
            'MAP16': 'D_DEAD2',
            'MAP17': 'D_STLKS3',
            'MAP18': 'D_ROMERO',
            'MAP19': 'D_SHAWN2',
            'MAP20': 'D_MESSAG',
            'MAP21': 'D_COUNT2',
            'MAP22': 'D_DDTBL3',
            'MAP23': 'D_AMPIE',
            'MAP24': 'D_THEDA3',
            'MAP25': 'D_ADRIAN',
            'MAP26': 'D_MESSG2',
            'MAP27': 'D_ROMER2',
            'MAP28': 'D_TENSE',
            'MAP29': 'D_SHAWN3',
            'MAP30': 'D_OPENIN',
            'MAP31': 'D_EVIL',
            'MAP32': 'D_ULTIMA',
        },
        'extra': {
            'D_DM2TTL',
            'D_DM2INT',
            'D_READ_M',
        }
    },

    Game.HERETIC: {
        'maps': {
            'E1M1': 'MUS_E1M1',
            'E1M2': 'MUS_E1M2',
            'E1M3': 'MUS_E1M3',
            'E1M4': 'MUS_E1M4',
            'E1M5': 'MUS_E1M5',
            'E1M6': 'MUS_E1M6',
            'E1M7': 'MUS_E1M7',
            'E1M8': 'MUS_E1M8',
            'E1M9': 'MUS_E1M9',
            'E2M1': 'MUS_E2M1',
            'E2M2': 'MUS_E2M2',
            'E2M3': 'MUS_E2M3',
            'E2M4': 'MUS_E2M4',
            'E2M5': 'MUS_E1M4',
            'E2M6': 'MUS_E2M6',
            'E2M7': 'MUS_E2M7',
            'E2M8': 'MUS_E2M8',
            'E2M9': 'MUS_E2M9',
            'E3M1': 'MUS_E1M1',
            'E3M2': 'MUS_E3M2',
            'E3M3': 'MUS_E3M3',
            'E3M4': 'MUS_E1M6',
            'E3M5': 'MUS_E1M3',
            'E3M6': 'MUS_E1M2',
            'E3M7': 'MUS_E1M5',
            'E3M8': 'MUS_E1M9',
            'E3M9': 'MUS_E2M6',
            'E4M1': 'MUS_E1M6',
            'E4M2': 'MUS_E1M2',
            'E4M3': 'MUS_E1M3',
            'E4M4': 'MUS_E1M4',
            'E4M5': 'MUS_E1M5',
            'E4M6': 'MUS_E1M1',
            'E4M7': 'MUS_E1M7',
            'E4M8': 'MUS_E1M8',
            'E4M9': 'MUS_E1M9',
            'E5M1': 'MUS_E2M1',
            'E5M2': 'MUS_E2M2',
            'E5M3': 'MUS_E2M3',
            'E5M4': 'MUS_E2M4',
            'E5M5': 'MUS_E1M4',
            'E5M6': 'MUS_E2M6',
            'E5M7': 'MUS_E2M7',
            'E5M8': 'MUS_E2M8',
            'E5M9': 'MUS_E2M9',
            'E6M1': 'MUS_E3M2',
            'E6M2': 'MUS_E3M3',
            'E6M3': 'MUS_E1M6',
        },
        'extra': {
            'MUS_TITL',
            'MUS_INTR',
            'MUS_CPTD',
        }
    },

    Game.HEXEN: {
        'maps': {
            'MAP01': 'winnowr',
            'MAP02': 'jachr',
            'MAP03': 'simonr',
            'MAP04': 'wutzitr',
            'MAP05': 'falconr',
            'MAP06': 'levelr',
            'MAP07': 'chartr',
            'MAP08': 'swampr',
            'MAP09': 'deepr',
            'MAP10': 'fubasr',
            'MAP11': 'grover',
            'MAP12': 'fortr',

            'MAP13': 'cryptr',
            'MAP14': 'swampr',

            'MAP21': 'foojar',
            'MAP22': 'sixater',
            'MAP23': 'wobabyr',
            'MAP24': 'cryptr',
            'MAP25': 'fantar',
            'MAP26': 'blechr',
            'MAP27': 'voidr',
            'MAP28': 'chap_1r',
            'MAP29': 'chap_2r',
            'MAP30': 'chap_3r',
            'MAP31': 'chap_4r',
            'MAP32': 'chippyr',
            'MAP33': 'percr',
            'MAP34': 'secretr',
            'MAP35': 'bonesr',
            'MAP36': 'octor',
            'MAP37': 'rithmr',
            'MAP38': 'stalkr',
            'MAP39': 'borkr',
            'MAP40': 'crucibr',
        },
        'extra': {
            'hexen',
            'hub',
            'hall',
            'orb',
            'chess',
            'chartr',
            'chap_2r',
        }
    },

    Game.STRIFE: {
        'maps': {
            'MAP01': 'D_ACTION',
            'MAP02': 'D_TAVERN',
            'MAP03': 'D_DANGER',
            'MAP04': 'D_FAST',
            'MAP05': 'D_INTRO',
            'MAP06': 'D_DARKER',
            'MAP07': 'D_STRIKE',
            'MAP08': 'D_SLIDE',
            'MAP09': 'D_TRIBAL',
            'MAP10': 'D_MARCH',
            'MAP11': 'D_DANGER',
            'MAP12': 'D_MOOD',
            'MAP13': 'D_CASTLE',
            'MAP14': 'D_DARKER',
            'MAP15': 'D_ACTION',
            'MAP16': 'D_FIGHT',
            'MAP17': 'D_SPENSE',
            'MAP18': 'D_SLIDE',
            'MAP19': 'D_STRIKE',
            'MAP20': 'D_DARK',
            'MAP21': 'D_TECH',
            'MAP22': 'D_SLIDE',
            'MAP23': 'D_DRONE',
            'MAP24': 'D_PANTHR',
            'MAP25': 'D_SAD',
            'MAP26': 'D_INSTRY',
            'MAP27': 'D_TECH',
            'MAP28': 'D_ACTION',
            'MAP29': 'D_INSTRY',
            'MAP30': 'D_DRONE',
            'MAP31': 'D_FIGHT',
            'MAP32': 'D_MAP1',
            'MAP33': 'D_MAP2',
            'MAP34': 'D_MAP3',
            'MAP35': 'D_TRIBAL',
            'MAP36': 'D_MARCH',
            'MAP37': 'D_STRIKE',
            'MAP38': 'D_TRIBAL',
        },
        'extra': {
            'D_HAPPY',
            'D_END',
            'D_LOGO',
        }
    },

    Game.DOOM64: {
        'maps': {
            'MAP01': 'MUSAMB04',
            'MAP02': 'MUSAMB05',
            'MAP03': 'MUSAMB13',
            'MAP04': 'MUSAMB12',
            'MAP05': 'MUSAMB09',
            'MAP06': 'MUSAMB15',
            'MAP07': 'MUSAMB16',
            'MAP08': 'MUSAMB18',
            'MAP09': 'MUSAMB03',
            'MAP10': 'MUSAMB06',
            'MAP11': 'MUSAMB07',
            'MAP12': 'MUSAMB10',
            'MAP13': 'MUSAMB01',
            'MAP14': 'MUSAMB14',
            'MAP15': 'MUSAMB19',
            'MAP16': 'MUSAMB05',
            'MAP17': 'MUSAMB11',
            'MAP18': 'MUSAMB02',
            'MAP19': 'MUSAMB08',
            'MAP20': 'MUSAMB20',
            'MAP21': 'MUSAMB17',
            'MAP22': 'MUSAMB09',
            'MAP23': 'MUSAMB16',
            'MAP24': 'MUSAMB06',
            'MAP25': 'MUSAMB05',
            'MAP26': 'MUSAMB06',
            'MAP27': 'MUSAMB02',
            'MAP28': 'MUSAMB07',
            'MAP29': 'MUSAMB09',
            'MAP30': 'MUSAMB10',
            'MAP31': 'MUSAMB11',
            'MAP32': 'MUSAMB12',
            'MAP33': 'MUSINTRO',
            'MAP34': 'MUSAMB08',
            'MAP35': 'MUSAMB03',
            'MAP36': 'MUSAMB19',
            'MAP37': 'MUSAMB02',
            'MAP38': 'MUSAMB13',
            'MAP39': 'MUSAMB06',
            'MAP40': 'MUSAMB09',
        },
        'extra': {
            'MUSFINAL',
            'MUSDONE',
            'MUSINTRO',
            'MUSTITLE',
        }
    }
}
