# Default strings defined in gzdoom.pk3
from indexer.game import Game

BUILTIN_STRINGS = {
    'MUSIC_E1M1': 'd_e1m1',
    'MUSIC_E1M2': 'd_e1m2',
    'MUSIC_E1M3': 'd_e1m3',
    'MUSIC_E1M4': 'd_e1m4',
    'MUSIC_E1M5': 'd_e1m5',
    'MUSIC_E1M6': 'd_e1m6',
    'MUSIC_E1M7': 'd_e1m7',
    'MUSIC_E1M8': 'd_e1m8',
    'MUSIC_E1M9': 'd_e1m9',
    'MUSIC_E2M1': 'd_e2m1',
    'MUSIC_E2M2': 'd_e2m2',
    'MUSIC_E2M3': 'd_e2m3',
    'MUSIC_E2M4': 'd_e2m4',
    'MUSIC_E2M5': 'd_e2m5',
    'MUSIC_E2M6': 'd_e2m6',
    'MUSIC_E2M7': 'd_e2m7',
    'MUSIC_E2M8': 'd_e2m8',
    'MUSIC_E2M9': 'd_e2m9',
    'MUSIC_E3M1': 'd_e3m1',
    'MUSIC_E3M2': 'd_e3m2',
    'MUSIC_E3M3': 'd_e3m3',
    'MUSIC_E3M4': 'd_e3m4',
    'MUSIC_E3M5': 'd_e3m5',
    'MUSIC_E3M6': 'd_e3m6',
    'MUSIC_E3M7': 'd_e3m7',
    'MUSIC_E3M8': 'd_e3m8',
    'MUSIC_E3M9': 'd_e3m9',
    'MUSIC_INTER': 'd_inter',
    'MUSIC_INTRO': 'd_intro',
    'MUSIC_BUNNY': 'd_bunny',
    'MUSIC_VICTOR': 'd_victor',
    'MUSIC_INTROA': 'd_introa',

    'MUSIC_RUNNIN': 'd_runnin',
    'MUSIC_STALKS': 'd_stalks',
    'MUSIC_COUNTD': 'd_countd',
    'MUSIC_BETWEE': 'd_betwee',
    'MUSIC_DOOM': 'd_doom',
    'MUSIC_THE_DA': 'd_the_da',
    'MUSIC_SHAWN': 'd_shawn',
    'MUSIC_DDTBLU': 'd_ddtblu',
    'MUSIC_IN_CIT': 'd_in_cit',
    'MUSIC_DEAD': 'd_dead',
    'MUSIC_STLKS2': 'd_stlks2',
    'MUSIC_THEDA2': 'd_theda2',
    'MUSIC_DOOM2': 'd_doom2',
    'MUSIC_DDTBL2': 'd_ddtbl2',
    'MUSIC_RUNNI2': 'd_runni2',
    'MUSIC_DEAD2': 'd_dead2',
    'MUSIC_STLKS3': 'd_stlks3',
    'MUSIC_ROMERO': 'd_romero',
    'MUSIC_SHAWN2': 'd_shawn2',
    'MUSIC_MESSAG': 'd_messag',
    'MUSIC_COUNT2': 'd_count2',
    'MUSIC_DDTBL3': 'd_ddtbl3',
    'MUSIC_AMPIE': 'd_ampie',
    'MUSIC_THEDA3': 'd_theda3',
    'MUSIC_ADRIAN': 'd_adrian',
    'MUSIC_MESSG2': 'd_messg2',
    'MUSIC_ROMER2': 'd_romer2',
    'MUSIC_TENSE': 'd_tense',
    'MUSIC_SHAWN3': 'd_shawn3',
    'MUSIC_OPENIN': 'd_openin',
    'MUSIC_EVIL': 'd_evil',
    'MUSIC_ULTIMA': 'd_ultima',
    'MUSIC_READ_M': 'd_read_m',
    'MUSIC_DM2TTL': 'd_dm2ttl',
    'MUSIC_DM2INT': 'd_dm2int',

    # These keys exist because they are valid, but we do
    # not need default names in the database.
    'HUSTR_E1M1': None,
    'HUSTR_E1M2': None,
    'HUSTR_E1M3': None,
    'HUSTR_E1M4': None,
    'HUSTR_E1M5': None,
    'HUSTR_E1M6': None,
    'HUSTR_E1M7': None,
    'HUSTR_E1M8': None,
    'HUSTR_E1M9': None,
    'HUSTR_E1M10': None,
    'HUSTR_E2M1': None,
    'HUSTR_E2M2': None,
    'HUSTR_E2M3': None,
    'HUSTR_E2M4': None,
    'HUSTR_E2M5': None,
    'HUSTR_E2M6': None,
    'HUSTR_E2M7': None,
    'HUSTR_E2M8': None,
    'HUSTR_E2M9': None,
    'HUSTR_E3M1': None,
    'HUSTR_E3M2': None,
    'HUSTR_E3M3': None,
    'HUSTR_E3M4': None,
    'HUSTR_E3M5': None,
    'HUSTR_E3M6': None,
    'HUSTR_E3M7': None,
    'HUSTR_E3M8': None,
    'HUSTR_E3M9': None,
    'HUSTR_E4M1': None,
    'HUSTR_E4M2': None,
    'HUSTR_E4M3': None,
    'HUSTR_E4M4': None,
    'HUSTR_E4M5': None,
    'HUSTR_E4M6': None,
    'HUSTR_E4M7': None,
    'HUSTR_E4M8': None,
    'HUSTR_E4M9': None,

    'HUSTR_1': None,
    'HUSTR_2': None,
    'HUSTR_3': None,
    'HUSTR_4': None,
    'HUSTR_5': None,
    'HUSTR_6': None,
    'HUSTR_7': None,
    'HUSTR_8': None,
    'HUSTR_9': None,
    'HUSTR_10': None,
    'HUSTR_11': None,
    'HUSTR_12': None,
    'HUSTR_13': None,
    'HUSTR_14': None,
    'HUSTR_15': None,
    'HUSTR_16': None,
    'HUSTR_17': None,
    'HUSTR_18': None,
    'HUSTR_19': None,
    'HUSTR_20': None,
    'HUSTR_21': None,
    'HUSTR_22': None,
    'HUSTR_23': None,
    'HUSTR_24': None,
    'HUSTR_25': None,
    'HUSTR_26': None,
    'HUSTR_27': None,
    'HUSTR_28': None,
    'HUSTR_29': None,
    'HUSTR_30': None,
    'HUSTR_31': None,
    'HUSTR_32': None,
    'HUSTR_31B': None,
    'HUSTR_32B': None,
    'HUSTR_33': None,

    'NHUSTR_1': None,
    'NHUSTR_2': None,
    'NHUSTR_3': None,
    'NHUSTR_4': None,
    'NHUSTR_5': None,
    'NHUSTR_6': None,
    'NHUSTR_7': None,
    'NHUSTR_8': None,
    'NHUSTR_9': None,

    'PHUSTR_1': None,
    'PHUSTR_2': None,
    'PHUSTR_3': None,
    'PHUSTR_4': None,
    'PHUSTR_5': None,
    'PHUSTR_6': None,
    'PHUSTR_7': None,
    'PHUSTR_8': None,
    'PHUSTR_9': None,
    'PHUSTR_10': None,
    'PHUSTR_11': None,
    'PHUSTR_12': None,
    'PHUSTR_13': None,
    'PHUSTR_14': None,
    'PHUSTR_15': None,
    'PHUSTR_16': None,
    'PHUSTR_17': None,
    'PHUSTR_18': None,
    'PHUSTR_19': None,
    'PHUSTR_20': None,
    'PHUSTR_21': None,
    'PHUSTR_22': None,
    'PHUSTR_23': None,
    'PHUSTR_24': None,
    'PHUSTR_25': None,
    'PHUSTR_26': None,
    'PHUSTR_27': None,
    'PHUSTR_28': None,
    'PHUSTR_29': None,
    'PHUSTR_30': None,
    'PHUSTR_31': None,
    'PHUSTR_32': None,

    'THUSTR_1': None,
    'THUSTR_2': None,
    'THUSTR_3': None,
    'THUSTR_4': None,
    'THUSTR_5': None,
    'THUSTR_6': None,
    'THUSTR_7': None,
    'THUSTR_8': None,
    'THUSTR_9': None,
    'THUSTR_10': None,
    'THUSTR_11': None,
    'THUSTR_12': None,
    'THUSTR_13': None,
    'THUSTR_14': None,
    'THUSTR_15': None,
    'THUSTR_16': None,
    'THUSTR_17': None,
    'THUSTR_18': None,
    'THUSTR_19': None,
    'THUSTR_20': None,
    'THUSTR_21': None,
    'THUSTR_22': None,
    'THUSTR_23': None,
    'THUSTR_24': None,
    'THUSTR_25': None,
    'THUSTR_26': None,
    'THUSTR_27': None,
    'THUSTR_28': None,
    'THUSTR_29': None,
    'THUSTR_30': None,
    'THUSTR_31': None,
    'THUSTR_32': None,

    'HHUSTR_E1M1': None,
    'HHUSTR_E1M2': None,
    'HHUSTR_E1M3': None,
    'HHUSTR_E1M4': None,
    'HHUSTR_E1M5': None,
    'HHUSTR_E1M6': None,
    'HHUSTR_E1M7': None,
    'HHUSTR_E1M8': None,
    'HHUSTR_E1M9': None,
    'HHUSTR_E2M1': None,
    'HHUSTR_E2M2': None,
    'HHUSTR_E2M3': None,
    'HHUSTR_E2M4': None,
    'HHUSTR_E2M5': None,
    'HHUSTR_E2M6': None,
    'HHUSTR_E2M7': None,
    'HHUSTR_E2M8': None,
    'HHUSTR_E2M9': None,
    'HHUSTR_E3M1': None,
    'HHUSTR_E3M2': None,
    'HHUSTR_E3M3': None,
    'HHUSTR_E3M4': None,
    'HHUSTR_E3M5': None,
    'HHUSTR_E3M6': None,
    'HHUSTR_E3M7': None,
    'HHUSTR_E3M8': None,
    'HHUSTR_E3M9': None,
    'HHUSTR_E4M1': None,
    'HHUSTR_E4M2': None,
    'HHUSTR_E4M3': None,
    'HHUSTR_E4M4': None,
    'HHUSTR_E4M5': None,
    'HHUSTR_E4M6': None,
    'HHUSTR_E4M7': None,
    'HHUSTR_E4M8': None,
    'HHUSTR_E4M9': None,
    'HHUSTR_E5M1': None,
    'HHUSTR_E5M2': None,
    'HHUSTR_E5M3': None,
    'HHUSTR_E5M4': None,
    'HHUSTR_E5M5': None,
    'HHUSTR_E5M6': None,
    'HHUSTR_E5M7': None,
    'HHUSTR_E5M8': None,
    'HHUSTR_E5M9': None,

    'TXT_STRIFE_MAP01': None,
    'TXT_STRIFE_MAP02': None,
    'TXT_STRIFE_MAP03': None,
    'TXT_STRIFE_MAP04': None,
    'TXT_STRIFE_MAP05': None,
    'TXT_STRIFE_MAP06': None,
    'TXT_STRIFE_MAP07': None,
    'TXT_STRIFE_MAP08': None,
    'TXT_STRIFE_MAP09': None,
    'TXT_STRIFE_MAP10': None,
    'TXT_STRIFE_MAP11': None,
    'TXT_STRIFE_MAP12': None,
    'TXT_STRIFE_MAP13': None,
    'TXT_STRIFE_MAP14': None,
    'TXT_STRIFE_MAP15': None,
    'TXT_STRIFE_MAP16': None,
    'TXT_STRIFE_MAP17': None,
    'TXT_STRIFE_MAP18': None,
    'TXT_STRIFE_MAP19': None,
    'TXT_STRIFE_MAP20': None,
    'TXT_STRIFE_MAP21': None,
    'TXT_STRIFE_MAP22': None,
    'TXT_STRIFE_MAP23': None,
    'TXT_STRIFE_MAP24': None,
    'TXT_STRIFE_MAP25': None,
    'TXT_STRIFE_MAP26': None,
    'TXT_STRIFE_MAP27': None,
    'TXT_STRIFE_MAP28': None,
    'TXT_STRIFE_MAP29': None,
    'TXT_STRIFE_MAP30': None,
    'TXT_STRIFE_MAP31': None,
    'TXT_STRIFE_MAP32': None,
    'TXT_STRIFE_MAP33': None,
    'TXT_STRIFE_MAP34': None,
    'TXT_STRIFE_MAP35': None,
    'TXT_STRIFE_MAP36': None,
    'TXT_STRIFE_MAP37': None,
    'TXT_STRIFE_MAP38': None,

    'TXT_HEXEN_MAP01': None,
    'TXT_HEXEN_MAP02': None,
    'TXT_HEXEN_MAP03': None,
    'TXT_HEXEN_MAP04': None,
    'TXT_HEXEN_MAP05': None,
    'TXT_HEXEN_MAP06': None,
    'TXT_HEXEN_MAP13': None,
    'TXT_HEXEN_MAP08': None,
    'TXT_HEXEN_MAP09': None,
    'TXT_HEXEN_MAP10': None,
    'TXT_HEXEN_MAP11': None,
    'TXT_HEXEN_MAP12': None,
    'TXT_HEXEN_MAP27': None,
    'TXT_HEXEN_MAP28': None,
    'TXT_HEXEN_MAP30': None,
    'TXT_HEXEN_MAP31': None,
    'TXT_HEXEN_MAP32': None,
    'TXT_HEXEN_MAP33': None,
    'TXT_HEXEN_MAP34': None,
    'TXT_HEXEN_MAP21': None,
    'TXT_HEXEN_MAP22': None,
    'TXT_HEXEN_MAP23': None,
    'TXT_HEXEN_MAP24': None,
    'TXT_HEXEN_MAP25': None,
    'TXT_HEXEN_MAP26': None,
    'TXT_HEXEN_MAP35': None,
    'TXT_HEXEN_MAP36': None,
    'TXT_HEXEN_MAP37': None,
    'TXT_HEXEN_MAP38': None,
    'TXT_HEXEN_MAP39': None,
    'TXT_HEXEN_MAP40': None,

    'TXT_HEXDD_MAP41': None,
    'TXT_HEXDD_MAP42': None,
    'TXT_HEXDD_MAP43': None,
    'TXT_HEXDD_MAP44': None,
    'TXT_HEXDD_MAP45': None,
    'TXT_HEXDD_MAP46': None,
    'TXT_HEXDD_MAP47': None,
    'TXT_HEXDD_MAP48': None,
    'TXT_HEXDD_MAP49': None,
    'TXT_HEXDD_MAP50': None,
    'TXT_HEXDD_MAP51': None,
    'TXT_HEXDD_MAP52': None,
    'TXT_HEXDD_MAP53': None,
    'TXT_HEXDD_MAP54': None,
    'TXT_HEXDD_MAP55': None,
    'TXT_HEXDD_MAP56': None,
    'TXT_HEXDD_MAP57': None,
    'TXT_HEXDD_MAP58': None,
    'TXT_HEXDD_MAP59': None,
    'TXT_HEXDD_MAP60': None,
    'TXT_HEXDD_MAP33': None,
    'TXT_HEXDD_MAP34': None,
    'TXT_HEXDD_MAP35': None,
    'TXT_HEXDD_MAP36': None,
    'TXT_HEXDD_MAP37': None,
    'TXT_HEXDD_MAP38': None,

    'CHUSTR_E1M1': None,
    'CHUSTR_E1M2': None,
    'CHUSTR_E1M3': None,
    'CHUSTR_E1M4': None,
    'CHUSTR_E1M5': None,
}

MUSIC_NAMES_DOOM = {
    'E1M1': 'd_e1m1',
    'E1M2': 'd_e1m2',
    'E1M3': 'd_e1m3',
    'E1M4': 'd_e1m4',
    'E1M5': 'd_e1m5',
    'E1M6': 'd_e1m6',
    'E1M7': 'd_e1m7',
    'E1M8': 'd_e1m8',
    'E1M9': 'd_e1m9',
    'E2M1': 'd_e2m1',
    'E2M2': 'd_e2m2',
    'E2M3': 'd_e2m3',
    'E2M4': 'd_e2m4',
    'E2M5': 'd_e2m5',
    'E2M6': 'd_e2m6',
    'E2M7': 'd_e2m7',
    'E2M8': 'd_e2m8',
    'E2M9': 'd_e2m9',
    'E3M1': 'd_e3m1',
    'E3M2': 'd_e3m2',
    'E3M3': 'd_e3m3',
    'E3M4': 'd_e3m4',
    'E3M5': 'd_e3m5',
    'E3M6': 'd_e3m6',
    'E3M7': 'd_e3m7',
    'E3M8': 'd_e3m8',
    'E3M9': 'd_e3m9',
    'E4M1': 'D_E3M4',
    'E4M2': 'D_E3M2',
    'E4M3': 'D_E3M3',
    'E4M4': 'D_E1M5',
    'E4M5': 'D_E2M7',
    'E4M6': 'D_E2M4',
    'E4M7': 'D_E2M6',
    'E4M8': 'D_E2M5',
    'E4M9': 'D_E1M9',
}

MUSIC_NAMES_DOOM2 = {
    'MAP01': 'D_RUNNIN',
    'MAP02': 'D_STALKS',
    'MAP03': 'D_COUNTD',
    'MAP04': 'D_BETWEE',
    'MAP05': 'D_DOOM',
    'MAP06': 'D_THE_DA',
    'MAP07': 'D_SHAWN',
    'MAP08': 'D_DDTBLU',
    'MAP09': 'D_IN_CIT',
    'MAP10': 'D_DEAD',
    'MAP11': 'D_STLKS2',
    'MAP12': 'D_THEDA2',
    'MAP13': 'D_DOOM2',
    'MAP14': 'D_DDTBL2',
    'MAP15': 'D_RUNNI2',
    'MAP16': 'D_DEAD2',
    'MAP17': 'D_STLKS3',
    'MAP18': 'D_ROMERO',
    'MAP19': 'D_SHAWN2',
    'MAP20': 'D_MESSAG',
    'MAP21': 'D_COUNT2',
    'MAP22': 'D_DDTBL3',
    'MAP23': 'D_AMPIE',
    'MAP24': 'D_THEDA3',
    'MAP25': 'D_ADRIAN',
    'MAP26': 'D_MESSG2',
    'MAP27': 'D_ROMER2',
    'MAP28': 'D_TENSE',
    'MAP29': 'D_SHAWN3',
    'MAP30': 'D_OPENIN',
    'MAP31': 'D_EVIL',
    'MAP32': 'D_ULTIMA',
}

MUSIC_NAMES_HERETIC = {
    'E1M1': 'MUS_E1M1',
    'E1M2': 'MUS_E1M2',
    'E1M3': 'MUS_E1M3',
    'E1M4': 'MUS_E1M4',
    'E1M5': 'MUS_E1M5',
    'E1M6': 'MUS_E1M6',
    'E1M7': 'MUS_E1M7',
    'E1M8': 'MUS_E1M8',
    'E1M9': 'MUS_E1M9',
    'E2M1': 'MUS_E2M1',
    'E2M2': 'MUS_E2M2',
    'E2M3': 'MUS_E2M3',
    'E2M4': 'MUS_E2M4',
    'E2M5': 'MUS_E1M4',
    'E2M6': 'MUS_E2M6',
    'E2M7': 'MUS_E2M7',
    'E2M8': 'MUS_E2M8',
    'E2M9': 'MUS_E2M9',
    'E3M1': 'MUS_E1M1',
    'E3M2': 'MUS_E3M2',
    'E3M3': 'MUS_E3M3',
    'E3M4': 'MUS_E1M6',
    'E3M5': 'MUS_E1M3',
    'E3M6': 'MUS_E1M2',
    'E3M7': 'MUS_E1M5',
    'E3M8': 'MUS_E1M9',
    'E3M9': 'MUS_E2M6',
    'E4M1': 'MUS_E1M6',
    'E4M2': 'MUS_E1M2',
    'E4M3': 'MUS_E1M3',
    'E4M4': 'MUS_E1M4',
    'E4M5': 'MUS_E1M5',
    'E4M6': 'MUS_E1M1',
    'E4M7': 'MUS_E1M7',
    'E4M8': 'MUS_E1M8',
    'E4M9': 'MUS_E1M9',
    'E5M1': 'MUS_E2M1',
    'E5M2': 'MUS_E2M2',
    'E5M3': 'MUS_E2M3',
    'E5M4': 'MUS_E2M4',
    'E5M5': 'MUS_E1M4',
    'E5M6': 'MUS_E2M6',
    'E5M7': 'MUS_E2M7',
    'E5M8': 'MUS_E2M8',
    'E5M9': 'MUS_E2M9',
    'E6M1': 'MUS_E3M2',
    'E6M2': 'MUS_E3M3',
    'E6M3': 'MUS_E1M6',
}

MUSIC_NAMES_HEXEN = {
    'MAP01': 'Winnowr',
    'MAP02': 'Jachr',
    'MAP03': 'Simonr',
    'MAP04': 'Wutzitr',
    'MAP05': 'Falconr',
    'MAP06': 'Levelr',
    'MAP07': 'Chartr',
    'MAP08': 'Swampr',
    'MAP09': 'Deepr',
    'MAP10': 'Fubasr',
    'MAP11': 'Grover',
    'MAP12': 'Fortr',

    'MAP13': 'cryptr',
    'MAP14': 'swampr',

    'MAP21': 'Foojar',
    'MAP22': 'Sixater',
    'MAP23': 'Wobabyr',
    'MAP24': 'Cryptr',
    'MAP25': 'Fantar',
    'MAP26': 'Blechr',
    'MAP27': 'Voidr',
    'MAP28': 'Chap_1r',
    'MAP29': 'Chap_2r',
    'MAP30': 'Chap_3r',
    'MAP31': 'Chap_4r',
    'MAP32': 'Chippyr',
    'MAP33': 'Percr',
    'MAP34': 'Secretr',
    'MAP35': 'Bonesr',
    'MAP36': 'Octor',
    'MAP37': 'Rithmr',
    'MAP38': 'Stalkr',
    'MAP39': 'Borkr',
    'MAP40': 'Crucibr',
}

MUSIC_NAMES_STRIFE = {
    'MAP01': 'D_ACTION',
    'MAP02': 'D_TAVERN',
    'MAP03': 'D_DANGER',
    'MAP04': 'D_FAST',
    'MAP05': 'D_INTRO',
    'MAP06': 'D_DARKER',
    'MAP07': 'D_STRIKE',
    'MAP08': 'D_SLIDE',
    'MAP09': 'D_TRIBAL',
    'MAP10': 'D_MARCH',
    'MAP11': 'D_DANGER',
    'MAP12': 'D_MOOD',
    'MAP13': 'D_CASTLE',
    'MAP14': 'D_DARKER',
    'MAP15': 'D_ACTION',
    'MAP16': 'D_FIGHT',
    'MAP17': 'D_SPENSE',
    'MAP18': 'D_SLIDE',
    'MAP19': 'D_STRIKE',
    'MAP20': 'D_DARK',
    'MAP21': 'D_TECH',
    'MAP22': 'D_SLIDE',
    'MAP23': 'D_DRONE',
    'MAP24': 'D_PANTHR',
    'MAP25': 'D_SAD',
    'MAP26': 'D_INSTRY',
    'MAP27': 'D_TECH',
    'MAP28': 'D_ACTION',
    'MAP29': 'D_INSTRY',
    'MAP30': 'D_DRONE',
    'MAP31': 'D_FIGHT',
    'MAP32': 'D_MAP1',
    'MAP33': 'D_MAP2',
    'MAP34': 'D_MAP3',
    'MAP35': 'D_TRIBAL',
    'MAP36': 'D_MARCH',
    'MAP37': 'D_STRIKE',
    'MAP38': 'D_TRIBAL',
}

MAP_TITLE_STRINGS = {
    Game.DOOM: {
        'E1M1: Hangar': 'E1M1',
        'E1M2: Nuclear Plant': 'E1M2',
        'E1M3: Toxin Refinery': 'E1M3',
        'E1M4: Command Control': 'E1M4',
        'E1M5: Phobos Lab': 'E1M5',
        'E1M6: Central Processing': 'E1M6',
        'E1M7: Computer Station': 'E1M7',
        'E1M8: Phobos Anomaly': 'E1M8',
        'E1M9: Military Base': 'E1M9',

        'E2M1: Deimos Anomaly': 'E2M1',
        'E2M2: Containment Area': 'E2M2',
        'E2M3: Refinery': 'E2M3',
        'E2M5: Command Center': 'E2M5',
        'E2M6: Halls of the Damned': 'E2M6',
        'E2M7: Spawning Vats': 'E2M7',
        'E2M8: Tower of Babel': 'E2M8',
        'E2M9: Fortress of Mystery': 'E2M9',

        'E3M1: Hell Keep': 'E3M1',
        'E3M2: Slough of Despair': 'E3M2',
        'E3M3: Pandemonium': 'E3M3',
        'E3M4: House of Pain': 'E3M4',
        'E3M5: Unholy Cathedral': 'E3M5',
        'E3M6: Mt. Erebus': 'E3M6',
        'E3M7: Limbo': 'E3M7',
        'E3M8: Dis': 'E3M8',
        'E3M9: Warrens': 'E3M9',

        'E4M1: Hell Beneath': 'E4M1',
        'E4M2: Perfect Hatred': 'E4M2',
        'E4M3: Sever The Wicked': 'E4M3',
        'E4M4: Unruly Evil': 'E4M4',
        'E4M5: They Will Repent': 'E4M5',
        'E4M6: Against Thee Wickedly': 'E4M6',
        'E4M7: And Hell Followed': 'E4M7',
        'E4M8: Unto The Cruel': 'E4M8',
        'E4M9: Fear': 'E4M9',

        'HUSTR_E1M1': 'E1M1',
        'HUSTR_E1M2': 'E1M2',
        'HUSTR_E1M3': 'E1M3',
        'HUSTR_E1M4': 'E1M4',
        'HUSTR_E1M5': 'E1M5',
        'HUSTR_E1M6': 'E1M6',
        'HUSTR_E1M7': 'E1M7',
        'HUSTR_E1M8': 'E1M8',
        'HUSTR_E1M9': 'E1M9',

        'HUSTR_E2M1': 'E2M1',
        'HUSTR_E2M2': 'E2M2',
        'HUSTR_E2M3': 'E2M3',
        'HUSTR_E2M4': 'E2M5',
        'HUSTR_E2M6': 'E2M6',
        'HUSTR_E2M7': 'E2M7',
        'HUSTR_E2M8': 'E2M8',
        'HUSTR_E2M9': 'E2M9',

        'HUSTR_E3M1': 'E3M1',
        'HUSTR_E3M2': 'E3M2',
        'HUSTR_E3M3': 'E3M3',
        'HUSTR_E3M4': 'E3M4',
        'HUSTR_E3M5': 'E3M5',
        'HUSTR_E3M6': 'E3M6',
        'HUSTR_E3M7': 'E3M7',
        'HUSTR_E3M8': 'E3M8',
        'HUSTR_E3M9': 'E3M9',

        'HUSTR_E4M1': 'E4M1',
        'HUSTR_E4M2': 'E4M2',
        'HUSTR_E4M3': 'E4M3',
        'HUSTR_E4M4': 'E4M4',
        'HUSTR_E4M5': 'E4M5',
        'HUSTR_E4M6': 'E4M6',
        'HUSTR_E4M7': 'E4M7',
        'HUSTR_E4M8': 'E4M8',
        'HUSTR_E4M9': 'E4M9',
    },
    Game.DOOM2: {
        'level 1: entryway': 'MAP01',
        'level 2: underhalls': 'MAP02',
        'level 3: the gantlet': 'MAP03',
        'level 4: the focus': 'MAP04',
        'level 5: the waste tunnels': 'MAP05',
        'level 6: the crusher': 'MAP06',
        'level 7: dead simple': 'MAP07',
        'level 8: tricks and traps': 'MAP08',
        'level 9: the pit': 'MAP09',
        'level 10: refueling base': 'MAP10',
        'level 11: \'o\' of destruction!': 'MAP11',

        'level 12: the factory': 'MAP12',
        'level 13: downtown': 'MAP13',
        'level 14: the inmost dens': 'MAP14',
        'level 15: industrial zone': 'MAP15',
        'level 16: suburbs': 'MAP16',
        'level 17: tenements': 'MAP17',
        'level 18: the courtyard': 'MAP18',
        'level 19: the citadel': 'MAP19',
        'level 20: gotcha!': 'MAP20',

        'level 21: nirvana': 'MAP21',
        'level 22: the catacombs': 'MAP22',
        'level 23: barrels o\' fun': 'MAP23',
        'level 24: the chasm': 'MAP24',
        'level 25: bloodfalls': 'MAP25',
        'level 26: the abandoned mines': 'MAP26',
        'level 27: monster condo': 'MAP27',
        'level 28: the spirit world': 'MAP28',
        'level 29: the living end': 'MAP29',
        'level 30: icon of sin': 'MAP30',

        'level 31: wolfenstein': 'MAP31',
        'level 32: grosse': 'MAP32',

        'HUSTR_1': 'MAP01',
        'HUSTR_2': 'MAP02',
        'HUSTR_3': 'MAP03',
        'HUSTR_4': 'MAP04',
        'HUSTR_5': 'MAP05',
        'HUSTR_6': 'MAP06',
        'HUSTR_7': 'MAP07',
        'HUSTR_8': 'MAP08',
        'HUSTR_9': 'MAP09',
        'HUSTR_10': 'MAP10',
        'HUSTR_11': 'MAP11',

        'HUSTR_12': 'MAP12',
        'HUSTR_13': 'MAP13',
        'HUSTR_14': 'MAP14',
        'HUSTR_15': 'MAP15',
        'HUSTR_16': 'MAP16',
        'HUSTR_17': 'MAP17',
        'HUSTR_18': 'MAP18',
        'HUSTR_19': 'MAP19',
        'HUSTR_20': 'MAP20',

        'HUSTR_21': 'MAP21',
        'HUSTR_22': 'MAP22',
        'HUSTR_23': 'MAP23',
        'HUSTR_24': 'MAP24',
        'HUSTR_25': 'MAP25',
        'HUSTR_26': 'MAP26',
        'HUSTR_27': 'MAP27',
        'HUSTR_28': 'MAP28',
        'HUSTR_29': 'MAP29',
        'HUSTR_30': 'MAP30',

        'HUSTR_31': 'MAP31',
        'HUSTR_32': 'MAP32',
    },
    Game.TNT: {
        'level 1: system control': 'MAP01',
        'level 2: human bbq': 'MAP02',
        'level 3: power control': 'MAP03',
        'level 4: wormhole': 'MAP04',
        'level 5: hanger': 'MAP05',
        'level 6: open season': 'MAP06',
        'level 7: prison': 'MAP07',
        'level 8: metal': 'MAP08',
        'level 9: stronghold': 'MAP09',
        'level 10: redemption': 'MAP10',
        'level 11: storage facility': 'MAP11',

        'level 12: crater': 'MAP12',
        'level 13: nukage processing': 'MAP13',
        'level 14: steel works': 'MAP14',
        'level 15: dead zone': 'MAP15',
        'level 16: deepest reaches': 'MAP16',
        'level 17: processing area': 'MAP17',
        'level 18: mill': 'MAP18',
        'level 19: shipping/respawning': 'MAP19',
        'level 20: central processing': 'MAP20',

        'level 21: administration center': 'MAP21',
        'level 22: habitat': 'MAP22',
        'level 23: lunar mining project': 'MAP23',
        'level 24: quarry': 'MAP24',
        'level 25: baron\'s den': 'MAP25',
        'level 26: ballistyx': 'MAP26',
        'level 27: mount pain': 'MAP27',
        'level 28: heck': 'MAP28',
        'level 29: river styx': 'MAP29',
        'level 30: last call': 'MAP30',

        'level 31: pharaoh': 'MAP31',
        'level 32: caribbean': 'MAP32',

        'THUSTR_1': 'MAP01',
        'THUSTR_2': 'MAP02',
        'THUSTR_3': 'MAP03',
        'THUSTR_4': 'MAP04',
        'THUSTR_5': 'MAP05',
        'THUSTR_6': 'MAP06',
        'THUSTR_7': 'MAP07',
        'THUSTR_8': 'MAP08',
        'THUSTR_9': 'MAP09',
        'THUSTR_10': 'MAP10',
        'THUSTR_11': 'MAP11',

        'THUSTR_12': 'MAP12',
        'THUSTR_13': 'MAP13',
        'THUSTR_14': 'MAP14',
        'THUSTR_15': 'MAP15',
        'THUSTR_16': 'MAP16',
        'THUSTR_17': 'MAP17',
        'THUSTR_18': 'MAP18',
        'THUSTR_19': 'MAP19',
        'THUSTR_20': 'MAP20',

        'THUSTR_21': 'MAP21',
        'THUSTR_22': 'MAP22',
        'THUSTR_23': 'MAP23',
        'THUSTR_24': 'MAP24',
        'THUSTR_25': 'MAP25',
        'THUSTR_26': 'MAP26',
        'THUSTR_27': 'MAP27',
        'THUSTR_28': 'MAP28',
        'THUSTR_29': 'MAP29',
        'THUSTR_30': 'MAP30',

        'THUSTR_31': 'MAP31',
        'THUSTR_32': 'MAP32',
    },
    Game.PLUTONIA: {
        'level 1: congo': 'MAP01',
        'level 2: well of souls': 'MAP02',
        'level 3: aztec': 'MAP03',
        'level 4: caged': 'MAP04',
        'level 5: ghost town': 'MAP05',
        'level 6: baron\'s lair': 'MAP06',
        'level 7: caughtyard': 'MAP07',
        'level 8: realm': 'MAP08',
        'level 9: abattoire': 'MAP09',
        'level 10: onslaught': 'MAP10',
        'level 11: hunted': 'MAP11',

        'level 12: speed': 'MAP12',
        'level 13: the crypt': 'MAP13',
        'level 14: genesis': 'MAP14',
        'level 15: the twilight': 'MAP15',
        'level 16: the omen': 'MAP16',
        'level 17: compound': 'MAP17',
        'level 18: neurosphere': 'MAP18',
        'level 19: nme': 'MAP19',
        'level 20: the death domain': 'MAP20',

        'level 21: slayer': 'MAP21',
        'level 22: impossible mission': 'MAP22',
        'level 23: tombstone': 'MAP23',
        'level 24: the final frontier': 'MAP24',
        'level 25: the temple of darkness': 'MAP25',
        'level 26: bunker': 'MAP26',
        'level 27: anti-christ': 'MAP27',
        'level 28: the sewers': 'MAP28',
        'level 29: odyssey of noises': 'MAP29',
        'level 30: the gateway of hell': 'MAP30',

        'level 31: cyberden': 'MAP31',
        'level 32: go 2 it': 'MAP32',

        'PHUSTR_1': 'MAP01',
        'PHUSTR_2': 'MAP02',
        'PHUSTR_3': 'MAP03',
        'PHUSTR_4': 'MAP04',
        'PHUSTR_5': 'MAP05',
        'PHUSTR_6': 'MAP06',
        'PHUSTR_7': 'MAP07',
        'PHUSTR_8': 'MAP08',
        'PHUSTR_9': 'MAP09',
        'PHUSTR_10': 'MAP10',
        'PHUSTR_11': 'MAP11',

        'PHUSTR_12': 'MAP12',
        'PHUSTR_13': 'MAP13',
        'PHUSTR_14': 'MAP14',
        'PHUSTR_15': 'MAP15',
        'PHUSTR_16': 'MAP16',
        'PHUSTR_17': 'MAP17',
        'PHUSTR_18': 'MAP18',
        'PHUSTR_19': 'MAP19',
        'PHUSTR_20': 'MAP20',

        'PHUSTR_21': 'MAP21',
        'PHUSTR_22': 'MAP22',
        'PHUSTR_23': 'MAP23',
        'PHUSTR_24': 'MAP24',
        'PHUSTR_25': 'MAP25',
        'PHUSTR_26': 'MAP26',
        'PHUSTR_27': 'MAP27',
        'PHUSTR_28': 'MAP28',
        'PHUSTR_29': 'MAP29',
        'PHUSTR_30': 'MAP30',

        'PHUSTR_31': 'MAP31',
        'PHUSTR_32': 'MAP32',
    },
    Game.HERETIC: {
        'E1M1:  THE DOCKS': 'E1M1',
        'E1M2:  THE DUNGEONS': 'E1M2',
        'E1M3:  THE GATEHOUSE': 'E1M3',
        'E1M4:  THE GUARD TOWER': 'E1M4',
        'E1M5:  THE CITADEL': 'E1M5',
        'E1M6:  THE CATHEDRAL': 'E1M6',
        'E1M7:  THE CRYPTS': 'E1M7',
        'E1M8:  HELL\'S MAW': 'E1M8',
        'E1M9:  THE GRAVEYARD': 'E1M9',

        'E2M1:  THE CRATER': 'E2M1',
        'E2M2:  THE LAVA PITS': 'E2M2',
        'E2M3:  THE RIVER OF FIRE': 'E2M3',
        'E2M4:  THE ICE GROTTO': 'E2M4',
        'E2M5:  THE CATACOMBS': 'E2M5',
        'E2M6:  THE LABYRINTH': 'E2M6',
        'E2M7:  THE GREAT HALL': 'E2M7',
        'E2M8:  THE PORTALS OF CHAOS': 'E2M8',
        'E2M9:  THE GLACIER': 'E2M9',

        'E3M1:  THE STOREHOUSE': 'E3M1',
        'E3M2:  THE CESSPOOL': 'E3M2',
        'E3M3:  THE CONFLUENCE': 'E3M3',
        'E3M4:  THE AZURE FORTRESS': 'E3M4',
        'E3M5:  THE OPHIDIAN LAIR': 'E3M5',
        'E3M6:  THE HALLS OF FEAR': 'E3M6',
        'E3M7:  THE CHASM': 'E3M7',
        'E3M8:  D\'SPARIL\'S KEEP': 'E3M8',
        'E3M9:  THE AQUIFER': 'E3M9',

        'E4M1:  CATAFALQUE': 'E4M1',
        'E4M2:  BLOCKHOUSE': 'E4M2',
        'E4M3:  AMBULATORY': 'E4M3',
        'E4M4:  SEPULCHER': 'E4M4',
        'E4M5:  GREAT STAIR': 'E4M5',
        'E4M6:  HALLS OF THE APOSTATE': 'E4M6',
        'E4M7:  RAMPARTS OF PERDITION': 'E4M7',
        'E4M8:  SHATTERED BRIDGE': 'E4M8',
        'E4M9:  MAUSOLEUM': 'E4M9',

        'E5M1:  OCHRE CLIFFS': 'E5M1',
        'E5M2:  RAPIDS': 'E5M2',
        'E5M3:  QUAY': 'E5M3',
        'E5M4:  COURTYARD': 'E5M4',
        'E5M5:  HYDRATYR': 'E5M5',
        'E5M6:  COLONNADE': 'E5M6',
        'E5M7:  FOETID MANSE': 'E5M7',
        'E5M8:  FIELD OF JUDGEMENT': 'E5M8',
        'E5M9:  SKEIN OF D\'SPARIL': 'E5M9',

        'HHUSTR_E1M1': 'E1M1',
        'HHUSTR_E1M2': 'E1M2',
        'HHUSTR_E1M3': 'E1M3',
        'HHUSTR_E1M4': 'E1M4',
        'HHUSTR_E1M5': 'E1M5',
        'HHUSTR_E1M6': 'E1M6',
        'HHUSTR_E1M7': 'E1M7',
        'HHUSTR_E1M8': 'E1M8',
        'HHUSTR_E1M9': 'E1M9',

        'HHUSTR_E2M1': 'E2M1',
        'HHUSTR_E2M2': 'E2M2',
        'HHUSTR_E2M3': 'E2M3',
        'HHUSTR_E2M4': 'E2M4',
        'HHUSTR_E2M5': 'E2M5',
        'HHUSTR_E2M6': 'E2M6',
        'HHUSTR_E2M7': 'E2M7',
        'HHUSTR_E2M8': 'E2M8',
        'HHUSTR_E2M9': 'E2M9',

        'HHUSTR_E3M1': 'E3M1',
        'HHUSTR_E3M2': 'E3M2',
        'HHUSTR_E3M3': 'E3M3',
        'HHUSTR_E3M4': 'E3M4',
        'HHUSTR_E3M5': 'E3M5',
        'HHUSTR_E3M6': 'E3M6',
        'HHUSTR_E3M7': 'E3M7',
        'HHUSTR_E3M8': 'E3M8',
        'HHUSTR_E3M9': 'E3M9',

        'HHUSTR_E4M1': 'E4M1',
        'HHUSTR_E4M2': 'E4M2',
        'HHUSTR_E4M3': 'E4M3',
        'HHUSTR_E4M4': 'E4M4',
        'HHUSTR_E4M5': 'E4M5',
        'HHUSTR_E4M6': 'E4M6',
        'HHUSTR_E4M7': 'E4M7',
        'HHUSTR_E4M8': 'E4M8',
        'HHUSTR_E4M9': 'E4M9',

        'HHUSTR_E5M1': 'E5M1',
        'HHUSTR_E5M2': 'E5M2',
        'HHUSTR_E5M3': 'E5M3',
        'HHUSTR_E5M4': 'E5M4',
        'HHUSTR_E5M5': 'E5M5',
        'HHUSTR_E5M6': 'E5M6',
        'HHUSTR_E5M7': 'E5M7',
        'HHUSTR_E5M8': 'E5M8',
        'HHUSTR_E5M9': 'E5M9',
    }
}
