openapi: 3.0.0

info:
  version: 1.0.0
  title: WadIndex API

components:
  schemas:

    Level:
      type: object
      properties:
        name:
          type: string
        title:
          type: string
        par_time:
          type: integer
        music:
          type: string
        next:
          type: string
        next_secret:
          type: string
        cluster:
          type: string
        format:
          type: string
        allow_jump:
          type: boolean
        allow_crouch:
          type: boolean
        stats:
          $ref: '#/components/schemas/LevelStats'
        screenshots:
          type: array
          items:
            $ref: '#/components/schemas/Image'

    LevelStats:
      type: object
      properties:
        things:
          type: integer
        lines:
          type: integer
        sectors:
          type: integer
        sides:
          type: integer

    Music:
      type: object
      properties:
        file_path:
          type: string
        type:
          type: string
        hash:
          type: string
        duration:
          type: integer

    Entry:
      type: object
      properties:
        title:
          type: string
        path:
          type: string
        size:
          type: integer
        timestamp:
          type: string
        game:
          type: string
        engine:
          type: string
        description:
          type: string
        tools_used:
          type: string
        build_time:
          type: string
        credits:
          type: string
        known_bugs:
          type: string
        comments:
          type: string
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        levels:
          type: array
          items:
            $ref: '#/components/schemas/Level'
        music:
          type: array
          items:
            $ref: '#/components/schemas/Music'
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        screenshots:
          type: array
          items:
            $ref: '#/components/schemas/Image'

    EntryTeaser:
      type: object
      properties:
        title:
          type: string
        path:
          type: string
        timestamp:
          type: string
        game:
          type: string
        description:
          type: string
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        level_count:
          type: integer
        thumbnail:
          type: array
          items:
            $ref: '#/components/schemas/Image'

    Image:
      type: object
      properties:
        path:
          type: string
        path_thumbnail:
          type: string
        name:
          type: string
        width:
          type: integer
        height:
          type: integer
        source:
          type: string

    Author:
      type: object
      properties:
        name:
          type: string
        full_name:
          type: string
        nickname:
          type: string

    Directory:
      type: object
      properties:
        name:
          type: string
        path:
          type: string

    DirectoryListing:
      type: object
      properties:
        directories:
          type: array
          items:
            $ref: '#/components/schemas/Directory'
        entries:
          type: array
          items:
            $ref: '#/components/schemas/EntryTeaser'

paths:
  /latest:
    get:
      description: Returns the latest entries.
      responses:
        '200':
          description: A list of the latest entry teasers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EntryTeaser'

  /images/random:
    get:
      description: Returns a small amount of random images.
      responses:
        '200':
          description: A list of random images.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'

  /search:
    get:
      description: Returns entries matching a search query.
      parameters:
        - name: key
          in: query
          description: The text to search for.
          schema:
            type: string
          required: true
        - name: filter_gameplay
          in: query
          description: Filter by the type of gameplay.
          schema:
            type: string
            enum: [singleplayer, deathmatch, cooperative]
        - name: filter_game
          in: query
          description: Filter by the type of game.
          schema:
            type: string
            enum: [doom, doom2, tnt, plutonia, heretic, hexen]
        - name: search_fields
          in: query
          description: Only search in specific fields.
          schema:
              type: array
              items:
                type: string
                enum: [title, description, authors, filename]
        - name: sort_field
          in: query
          description: Sort results by a property.
          schema:
            type: string
            enum: [relevance, title, date]
            default: relevance
        - name: sort_order
          in: query
          description: Result sorting order.
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: A list of entry teasers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EntryTeaser'

  /entry/{entry_path}:
    get:
      description: Returns all information of a single entry.
      parameters:
        - name: entry_path
          in: path
          description: Path of the entry to return a level from.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Entry information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entry'

  /level/{entry_path}/{level_name}:
    get:
      description: Returns all information of a single level.
      parameters:
        - name: entry_path
          in: path
          description: Path of the entry to return a level from.
          required: true
          schema:
            type: string
        - name: level_name
          in: path
          description: Lump name of the level to return.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Level information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Level'

  /music/{hash}:
    get:
      description: Returns all information of a single music track.
      parameters:
        - name: hash
          in: path
          description: Hash of the music track to return.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Music information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Music'

  /list/{path}:
    get:
      description: Returns all entries and subdirectories of a path.
      parameters:
        - name: path
          in: path
          description: Path of the directory listing to return.
          required: true
          schema:
            type: string
        - name: sort_field
          in: query
          description: Sort results by a property.
          schema:
            type: string
            enum: [title, date]
            default: relevance
        - name: sort_order
          in: query
          description: Result sorting order.
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Entries and subdirectories.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectoryListing'

  /author/{path_alias}:
    get:
      description: Returns all information of a single author.
      parameters:
        - name: path_alias
          in: path
          description: Path alias of the author to return.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Author information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
